
name: ablesci-checkin

on:
  workflow_dispatch: #手动执行
  schedule:          # 定时任务
    - cron: '40 13,23 * * *' #每日7点40,21点40，两个时间点执行任务
jobs:
  checkin:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Checkin
      run: |
        python3 ./ablesci.py    #要执行的py代码
      env: #设置secrets的环境变量
        ABLESCICOOKIE: ${{ secrets.ABLESCICOOKIE }}
        SCKEY: ${{ secrets.SCKEY }}  # 息知的XZKEY; secrets可填
